# general settings
name:  train_mambadiff_s1_seed101
model_type: MPI_Mamba_S1
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 101

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: PairedImageIRDataset
    dataroot_gt: /root/data1/R26MPIimage/realdata/train/label
    dataroot_lq: /root/data1/R26MPIimage/realdata/train/low
    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [32,32,32,32,32,32]             # Batch size per gpu
    iters: [20000,20000,20000,20000,20000,20000]
    gt_size: 64   # Max patch size for progressive training
    gt_sizes: [64,64,64,64,64,64]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: PairedImageIRDataset
    dataroot_gt: /root/data1/R26MPIimage/realdata/test/label
    dataroot_lq: /root/data1/R26MPIimage/realdata/test/low
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: Mamba
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [2,2,2,2]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  embed_dim: 64
  group: 4 # N=4*4

network_le:
  type: latent_encoder_gelu
  in_chans: 6
  embed_dim: 64 # same as above
  block_num: 6
  group: 4 # same as above
  stage: 1
  patch_expansion: 0.5
  channel_expansion: 4

# path
path:
  pretrain_network_g: ~
  param_key_g: params
  strict_load_g: true

  pretrain_network_le: ~
  param_key_g: params
  strict_load_le: true

  resume_state: ~

# training settings
train:
  total_iter: 100000
  warmup_iter: -1 # no warm up
  use_grad_clip: True

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [50000, 80000]       
    restart_weights: [1,1]
    eta_mins: [0.0002,0.000001]
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_total:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 4e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
